### PR TITLE
First commit presentation folder with data science presentation

### PR DESCRIPTION
**Pull request by Lextuga007**

### CODE REVIEW

**Comment by tomjemmett** [comment]
I don't think that this is going to be the best way to commit presentation, as the existing quarto build isn't going to have a clue how to include the pre-rendered presentations. Let me have a quick play

**Comment by Lextuga007** [comment]
Does this mean we can remove the pdf? *Secretly but not so secretly pleased* 😊

**Comment by tomjemmett** [comment]
I've used admin rights to merge this, more so to test the action actually works as intended

**Comment by tomjemmett** [comment]
looks like it's working, could you check the slides render as expected @ChrisBeeley ? https://the-strategy-unit.github.io/data_science/presentations/

**Comment by tomjemmett** [comment]
added a new issue for the presentations page in #10

**Comment by ChrisBeeley** [comment]
Love it love it love it!

**Pull request merged**
